-- ==============================================================
-- 09_apertura_productos.sql  (v2 — tabla public.items)
-- 161 productos desde Odoo v18
-- ON CONFLICT usa sku (único), items sin SKU usan INSERT...WHERE NOT EXISTS
-- ==============================================================

-- Categoria por defecto
INSERT INTO public.categorias (nombre, descripcion, activo)
VALUES ('General', 'Categoría general de productos', true)
ON CONFLICT (nombre) DO NOTHING;

-- Productos CON SKU → ON CONFLICT (sku)
INSERT INTO public.items (sku, nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
VALUES
  ('0033-000004', 'CAMARA OSMO POCKET 3 CREATOR COMBO(OK002)', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0001-000006', 'FILETE DE ATUN CAMPOMARCA', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.8, true),
  ('0001-000007', 'GASTOS DE PROTESTO DE LETRAS', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0001-000005', 'GASTOS DE REFINANCIACION DE LETRAS', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0200-020003', 'HILADO 100% ALGODON NE 21/1 PEINADO COMPACTADO INDIGO/AZUL', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 29.25, true),
  ('0700-070007', 'HILADO 10/1 ALGODON OPEND', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('1400-140003', 'HILADO 20/1 PEINADO COMPACTADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0200-020001', 'HILADO 21/1 INDIGO OPEN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.0, true),
  ('1400-140002', 'HILADO 24/1 PEINADO COMPACTADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0200-020007', 'HILADO 24/1 POLYCOTTON 48/52 PEINADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070009', 'HILADO 28/1 POLYCOTTON MELANGE 10%', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.46822, true),
  ('1400-140001', 'HILADO 30/1 PEINADO COMPACTADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0100-010002', 'HILADO 30/1 PEINADO COMPACTADO CRUDO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.875, true),
  ('0100-010007', 'HILADO 30/1 SPUN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.875, true),
  ('0100-010009', 'HILADO 30/1 SPUN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.875, true),
  ('0200-020002', 'HILADO ALGODON 21/1 INDIGO / Black', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 29.25, true),
  ('0200-020004', 'HILADO ALGODON 21/1 Indigo / Light Blue', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 29.25, true),
  ('0700-070006', 'HILADO ANILLO MELANGE 20/1 POLYCOTTON 10/90', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.46822, true),
  ('0200-020006', 'HILADO DE ALGODÓN 20/1 CARDADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 0.0, true),
  ('0200-020005', 'HILADO DE ALGODON 24/1 CARDADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0301-030027', 'HILADO POLYESTER 150/48-2 RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.6875, true),
  ('0300-030016', 'HILADO POLYESTER 150D/144F/1 DDBLACK-SHADE 5', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 9.375, true),
  ('0300-030017', 'HILADO POLYESTER 150D/144F/1 DDBLACK-SHADE 6', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 9.375, true),
  ('0300-030011', 'HILADO POLYESTER 150D/144F DDBLACK', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 9.375, true),
  ('0300-030012', 'HILADO POLYESTER 150D/144F DDBLACK', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 9.375, true),
  ('0300-030010', 'HILADO POLYESTER 150D/144F DD BLACK MC31536', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.86, true),
  ('0301-030020', 'HILADO POLYESTER 150D/144F RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.125, true),
  ('0301-030021', 'HILADO POLYESTER 150D/144F RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.6875, true),
  ('0301-030022', 'HILADO POLYESTER 150D/144F RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.13, true),
  ('0301-030025', 'HILADO POLYESTER 150D/144F RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.13, true),
  ('0301-030023', 'HILADO POLYESTER 150D/144F RW*', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.4875, true),
  ('0301-030028', 'HILADO POLYESTER 150D/48F-HIM', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.13, true),
  ('0301-030026', 'HILADO POLYESTER 150D/48F RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.13, true),
  ('0400-040033', 'HILADO POLYESTER 160D/144F DDBLACK', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 9.375, true),
  ('0400-040032', 'HILADO POLYESTER 160D/144F RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.13, true),
  ('0400-040030', 'HILADO POLYESTER 160D/34F RW', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.125, true),
  ('0400-040031', 'HILADO POLYESTER 160D/36F NIM RW SD', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.125, true),
  ('0100-010008', 'HILADO POLYESTER 28/1 SPUN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 0.0, true),
  ('0500-050045', 'HILADO POLYESTER 75/36 NIM', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.8375, true),
  ('0500-050040', 'HILADO POLYESTER 75/72 RW - HIM', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.95, true),
  ('0500-050041', 'HILADO POLYESTER 75/72 RW - SIM', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.8375, true),
  ('0500-050044', 'HILADO POLYESTER 75/72 RW - SIM', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.8375, true),
  ('0500-050042', 'HILADO POLYESTER 75D/72F', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0500-050043', 'HILADO POLYESTER 75D/72F SIM', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.355931, true),
  ('0301-030014', 'HILADO POLYESTER TEXTURIZADO 150D/144F NEGRO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.86, true),
  ('0600-060050', 'HILADO SPANDEX 20DN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 22.5, true),
  ('0600-060060', 'HILADO SPANDEX 30DN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 19.2, true),
  ('0600-060070', 'HILADO SPANDEX 40DN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0600-060081', 'HILADO SPANDEX 70DN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 19.85, true),
  ('0600-060080', 'HILADO SPANDEX 70DN', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 17.85, true),
  ('0700-070014', 'HILADO SPUN 10/1 AZULINO 38#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070010', 'HILADO SPUN 10/1 BLANCO OPTICO 2#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070004', 'HILADO SPUN 10/1 CRUDO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.46822, true),
  ('0700-070013', 'HILADO SPUN 10/1 NARANJA 22#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070011', 'HILADO SPUN 10/1 ROJO 20#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070012', 'HILADO SPUN 10/1 ROJO 2. 21#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070015', 'HILADO SPUN 10/1 VERDE 57#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070021', 'HILADO SPUN 20/1 AMARILLO 1. 31#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070022', 'HILADO SPUN 20/1 AMARILLO 2. 32#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070023', 'HILADO SPUN 20/1 AZULINO 38#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070025', 'HILADO SPUN 20/1 AZUL MARINO 45#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070024', 'HILADO SPUN 20/1 AZUL TIBETANO 44#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070026', 'HILADO SPUN 20/1 BEIGE 49#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070008', 'HILADO SPUN 20/1 BLACK', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070016', 'HILADO SPUN 20/1 BLANCO OPTICO 2#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070029', 'HILADO SPUN 20/1 MARRON 81#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070003', 'HILADO SPUN 20/1 MELANGE 12%', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.46822, true),
  ('0700-070020', 'HILADO SPUN 20/1 MORADO LIGHT 24#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070019', 'HILADO SPUN 20/1 NARANJA 22#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070001', 'HILADO SPUN 20/1 NEGRO RW AAAA', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070028', 'HILADO SPUN 20/1 PLOMO 70#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070017', 'HILADO SPUN 20/1 ROJO 20#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070018', 'HILADO SPUN 20/1 ROJO 2. 21#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070002', 'HILADO SPUN 20/1 RW AAAA', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.46822, true),
  ('0700-070027', 'HILADO SPUN 20/1 VERDE 57#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0100-010003', 'HILADO SPUN 30/1 #22 NARANJA', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 11.175, true),
  ('0100-010004', 'HILADO SPUN 30/1 #32 AMARILLO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 11.175, true),
  ('0100-010005', 'HILADO SPUN 30/1 #44 AZUL MARINO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 11.175, true),
  ('0700-070035', 'HILADO SPUN 30/1 AMARILLO 1. 31#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070036', 'HILADO SPUN 30/1 AMARILLO 2. 32#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070037', 'HILADO SPUN 30/1 AZULINO 38#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070039', 'HILADO SPUN 30/1 AZUL MARINO 45#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070038', 'HILADO SPUN 30/1 AZUL TIBETANO 44#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070040', 'HILADO SPUN 30/1 BEIGE 49#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0100-010010', 'HILADO SPUN 30/1 BLACK', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070030', 'HILADO SPUN 30/1 BLANCO OPTICO 2#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070043', 'HILADO SPUN 30/1 MARRON 81#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070034', 'HILADO SPUN 30/1 MORADO LIGHT 24#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070033', 'HILADO SPUN 30/1 NARANJA 22#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0100-010001', 'HILADO  SPUN 30/1 NEGRO AAA # 48', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 11.175, true),
  ('0700-070042', 'HILADO SPUN 30/1 PLOMO 70#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070031', 'HILADO SPUN 30/1 ROJO 20#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0700-070032', 'HILADO SPUN 30/1 ROJO 2. 21#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0100-010006', 'HILADO SPUN 30/1 RW AAAA CRUDO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 7.875, true),
  ('0700-070041', 'HILADO SPUN 30/1 VERDE 57#', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0301-030015', 'HILO FUSION 150D BLACK', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 11.440678, true),
  ('0001-000010', 'IGV', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0033-000003', 'LAPTOP HP CORE 17 1355U 240 G10 (81D42LT)', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0001-000012', 'OTROS GASTOS DE VENTAS', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('1200-120001', 'PAPER TOUCH-PPT', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('1200-120002', 'PAPER TOUCH-PPT ESTAMPADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 13.559312, true),
  ('0001-000014', 'SERVICIO DE LIMPIEZA', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1760.0, true),
  ('0600-060051', 'SPANDEX 20DN CURVOSOFT', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0600-060052', 'SPANDEX 20DN HF-2502', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0600-060053', 'SPANDEX 20DN HUAFON', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 6.0, true),
  ('0600-060061', 'SPANDEX 30DN HF-2502', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0600-060071', 'SPANDEX 40DN HF-2502', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0600-060082', 'SPANDEX 70DN HF-2502', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 4.237288, true),
  ('0600-060083', 'SPANDEX 70DN HUAFON', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.6, true),
  ('0001-000020', 'Table', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0001-000021', 'Table Leg', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0001-000022', 'Table Top', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0033-000002', 'TABLET SAMSUNG GALAXY TAB S7', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0033-000001', 'TABLET SAMSUNG TBS9-256 GB CREMA', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('1100-110001', 'TAFETA BOLSILLERO 1.60', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.5, true),
  ('1100-110002', 'TAFETA BOLSILLERO 1.60 ESTAMPADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.508475, true),
  ('1100-110003', 'TAFETA BOLSILLERO 1.60 OKTAGUNUX NEGRO Y MOSTAZA', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.508475, true),
  ('1100-110004', 'TAFETA BOLSILLERO 1.72', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.5, true),
  ('1100-110005', 'TAFETA BOLSILLERO 1.72 ESTAMPADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 5.508475, true),
  ('0090-009003', 'TELA DENIM 12 OZ', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009008', 'TELA DENIM AZUL SANF.', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009010', 'TELA DENIM CAMISERO SANFORIZADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009004', 'TELA DENIM COMFORT FORTE', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009009', 'TELA DENIM CONFORT AZUL', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009001', 'TELA DENIM PREMIUM MERCERIZADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009006', 'TELA DENIM SANFORIZADO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009002', 'TELA DENIM SANFORIZADO FORTE', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009005', 'TELA DENIM ST AZUL', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('1300-130001', 'TELA DENIM TRICOT', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009011', 'TELA DRILL STRETCH PESO:8OZ', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0090-009007', 'TELA DRIL RIGIDO MICRO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('1200-120003', 'TELA INDIGO BLUE 240', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 13.559312, true),
  ('1200-120004', 'TELA SUPLEX NEGRO', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 1.0, true),
  ('0001-000023', 'YOGURT GLORIA FRESA 1GL', 'mercaderia',
   (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
   'UND', 10.0, true)
ON CONFLICT (sku) DO UPDATE SET
  nombre       = EXCLUDED.nombre,
  precio_venta = EXCLUDED.precio_venta,
  tipo_item    = EXCLUDED.tipo_item,
  updated_at   = now();

-- Productos SIN SKU → INSERT solo si no existe por nombre
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'AD-VALOREM', 'servicio',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='AD-VALOREM');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'ALQUILERES', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='ALQUILERES');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'ARRENDAMIENTO DE BIENES', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='ARRENDAMIENTO DE BIENES');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'AVISO DE LLEGADA', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='AVISO DE LLEGADA');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'Boletin Quimico', 'servicio',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='Boletin Quimico');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'CAMIONETA BLANCO (TIGGO 8 PRO HYBRID 1.5T DHT PHEV FULL 2024 ) PLACA CUU-472', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='CAMIONETA BLANCO (TIGGO 8 PRO HYBRID 1.5T DHT PHEV FULL 2024 ) PLACA CUU-472');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'CAMIONETA CHERY TIGGO 8 PRO COLOR: PLATA AÑO: 2023 PLACA: CJD232', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='CAMIONETA CHERY TIGGO 8 PRO COLOR: PLATA AÑO: 2023 PLACA: CJD232');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'CLUB SOCIAL', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='CLUB SOCIAL');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'COMISION DE ADUANAS, GASTOS OPERATIVOS Y OTROS', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='COMISION DE ADUANAS, GASTOS OPERATIVOS Y OTROS');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'CVC ( CNTR SVC CHARGE )', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='CVC ( CNTR SVC CHARGE )');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'DESCUENTOS DIVERSOS', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='DESCUENTOS DIVERSOS');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'FLETE', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='FLETE');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'GASTOS IMPORTA', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='GASTOS IMPORTA');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'GATE IN - DEVOLUCIÓN DE CONTENEDOR', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='GATE IN - DEVOLUCIÓN DE CONTENEDOR');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'INTERES POR PRESTAMO', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='INTERES POR PRESTAMO');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'ISD Impuesto a la Salida de Divisas.', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='ISD Impuesto a la Salida de Divisas.');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'ISPS (Internacional para la Protección de Buques e Instalaciones Portuarias)', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='ISPS (Internacional para la Protección de Buques e Instalaciones Portuarias)');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'MOTO HERO MODELO: IGNITOR125 COLOR NEGRO AÑO 2026 PLACA:3103-HD', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='MOTO HERO MODELO: IGNITOR125 COLOR NEGRO AÑO 2026 PLACA:3103-HD');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'PRESTAMOS DIVERSOS', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='PRESTAMOS DIVERSOS');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'RENTA DE NO DOMICILIADOS', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='RENTA DE NO DOMICILIADOS');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'SEGURO DE TRANSPORTE DE CARGA (Insurance)', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='SEGURO DE TRANSPORTE DE CARGA (Insurance)');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'SERVICIO DE ALMACENAJE', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='SERVICIO DE ALMACENAJE');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'SERVICIO DE FLETE MARÍTIMO (Ocean Freight)', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='SERVICIO DE FLETE MARÍTIMO (Ocean Freight)');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'SERVICIO DE TRANSPORTE', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='SERVICIO DE TRANSPORTE');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'TAFETA BOLSILLERA NEGRA ESTAMPADO CORTINAS (SERVICIO)', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 6.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='TAFETA BOLSILLERA NEGRA ESTAMPADO CORTINAS (SERVICIO)');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'THC ( TERMINAL HANDLING CHARGE )', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='THC ( TERMINAL HANDLING CHARGE )');
INSERT INTO public.items (nombre, tipo_item, categoria_id, unidad_medida, precio_venta, activo)
SELECT 'VISTO BUENO', 'mercaderia',
       (SELECT id FROM public.categorias WHERE nombre='General' LIMIT 1),
       'UND', 1.0, true
WHERE NOT EXISTS (SELECT 1 FROM public.items WHERE nombre='VISTO BUENO');

-- Verificar: SELECT tipo_item, COUNT(*) FROM items GROUP BY tipo_item;